[package]
name = "stal-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["default", "derive"] }
env_logger = "0.11.3"
log = "0.4.21"
stal-core = { path = "../stal-core" }
