[package]
name = "stal-core"
version = "0.1.0"
edition = "2021"

[dependencies]
charabia = "0.8.11"
fsio = "0.4.0"
log = "0.4.21"
postcard = { version = "1.0.8", features = ["default", "alloc"] }
serde = { version = "1.0.203", features = ["derive"] }
text-splitter = "0.13.3"
thiserror = "1.0.61"
